# Quantum Machine Learning for Option Pricing — Distributed Experiment (Dask CPU)

## Overview

This notebook replicates the baseline experiment from `01_supervised_vs_unsupervised_qml_option_pricing.ipynb` with a key difference: **loss and gradient evaluations are parallelised across a local Dask cluster** instead of running sequentially on a single CPU thread.

The goal is to evaluate whether Dask-based parallelism reduces wall-clock training time for the same supervised/unsupervised QML experiment, without changing the model architecture, hyperparameters, or pricing methodology.

---

## Problem Setup

Identical to the baseline notebook:
- **Asset model:** Black-Scholes log-normal with $S_0=100$, $r=10\%$, $\sigma=25\%$, $T=1$ year
- **Strikes:** $K \in \{90, 100, 110\}$ (OTM, ATM, ITM)
- **Input feature:** log-moneyness $x_t = \log(S_T / K)$, rescaled to $[-\pi, \pi]$

---

## Dask Cluster Configuration

A `LocalCluster` is created at notebook startup with:
- **Workers:** 4 independent processes
- **Threads per worker:** 1 (avoids Python GIL contention)
- **Memory limit:** auto-managed by Dask
- **Dashboard:** disabled

The `dask_client` handle is passed into the `workflow_cfg` dictionary and forwarded to `adam_optimizer_loop`, which distributes individual loss/gradient evaluations across workers. If Dask is unavailable, the notebook falls back to sequential execution.

Resources are explicitly closed at the end of the notebook via `client.close()` and `cluster.close()`.

---

## Quantum Circuit Architecture

Identical to the baseline experiment:
- **Hardware-efficient ansatz** via `qml4var.architectures.hardware_efficient_ansatz`
- **Supervised mode:** 3 qubits/feature × 3 layers
- **Unsupervised mode:** 2 qubits/feature × 2 layers
- Circuit output interpreted as CDF; derivative gives PDF
- Gradients via **PyTorch autograd**

---

## Training Modes

### Supervised
- **Target:** Empirical CDF shifted to $[-0.5, 0.5]$
- **Loss:** MSE (0.9) + regularisation (0.1)
- **Learning rate:** 0.005 | **Dataset sizes:** 250, 500, 1000

### Unsupervised
- **Target:** No labels — distributional loss on PDF
- **Loss weights:** [0.2 PDF, 0.8 auxiliary]
- **Learning rate:** 0.1 | **Dataset sizes:** 1000, 2500, 5000

**Common settings:** Adam ($\beta_1=0.9$, $\beta_2=0.999$), early stopping (patience = 25, tol = $10^{-8}$), max 50 epochs.

These configurations are identical to the baseline, enabling a direct performance comparison.

---

## Option Pricing Method

Both supervised and unsupervised modes use **Method I — PDF-based Fourier pricing** exclusively:

1. Evaluate the trained circuit PDF on a 1024-point grid over $[-2\pi, 2\pi]$
2. Normalise the PDF to unit area
3. Compute Fourier coefficients $(A_k, B_k)$ of the PDF ($K=12$ terms)
4. Compute Fourier coefficients of the put payoff $h(x) = \max(K(1 - e^x), 0)$
5. Apply the pricing formula via `finance.fourier_price_v_t0`

> **Note:** Unlike the baseline notebook, this notebook does **not** use the Integration by Parts (Method II) formula for the unsupervised mode. The focus here is on training throughput via parallelism, not on pricing accuracy comparison between methods.

---

## Evaluation

Same metrics as the baseline:
- **Test MSE:** CDF prediction error on held-out test points
- **Estimated price vs. Black-Scholes price**
- **Runtime:** Seconds per training run (the primary comparison axis against the sequential baseline)

Results are aggregated over repetitions and plotted as price curves vs. dataset size per strike.

---

## Execution

- **Device:** CPU (Dask worker processes do not share GPU memory)
- **Parallelism:** 4-worker Dask `LocalCluster`
- **Debug mode:** Set `DEBUG_FAST_RUN = True` for a fast 2-epoch sanity check

In [ ]:
import sys
from time import perf_counter

import torch

sys.path.insert(0, "../src")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from finance import (
    bs_put_price,
    estimate_price_from_trained_pqc,
)
from qml4var.adam import adam_optimizer_loop
from qml4var.architectures import (
    hardware_efficient_ansatz,
    init_weights,
    normalize_data,
)
from qml4var.data_utils import (
    empirical_cdf,
    simulate_black_scholes_data_rescaled,
)
from qml4var.losses import torch_gradient
from qml4var.workflows import (
    qdml_loss_workflow,
    unsupervised_qdml_loss_workflow,
    workflow_for_cdf,
)

try:
    from tqdm.auto import tqdm
    TQDM_AVAILABLE = True
except Exception:
    TQDM_AVAILABLE = False

    class _NoTqdm:
        def __init__(self, total=None, desc=None, unit=None, disable=False):
            self.total = total
            self.n = 0
            self.disable = disable
            if not self.disable:
                print(f"{desc or 'Progress'} | total={total} {unit or ''}")

        def update(self, n=1):
            self.n += n

        def set_postfix(self, *args, **kwargs):
            return None

        def close(self):
            return None

    def tqdm(*args, **kwargs):
        return _NoTqdm(*args, **kwargs)

## 1. Global Setup

In [ ]:
# Black-Scholes parameters
S0 = 100.0
r = 0.10
sigma = 0.25
T = 1.0
STRIKES = [90, 100, 110]

# Domains
TRAIN_INTERVAL = (-2.0 * np.pi, 2.0 * np.pi)  # workflow domain
DATA_INTERVAL = (-1.0 * np.pi, 1.0 * np.pi)   # data interval after rescaling
ENCODING_INTERVAL = (-1.0 * np.pi, 1.0 * np.pi)
FEATURES_NUMBER = 1

# Fourier pricing setup
K_TERMS = 12
GRID_POINTS_FOURIER = 1024

# Optional: use local Dask cluster (CPU parallelism)
USE_LOCAL_DASK = True
DASK_N_WORKERS = 4
DASK_THREADS_PER_WORKER = 1
DASK_MEMORY_LIMIT = "auto"

DASK_CLIENT = None
_dask_cluster = None
if USE_LOCAL_DASK:
    try:
        from distributed import Client, LocalCluster
        _dask_cluster = LocalCluster(
            n_workers=DASK_N_WORKERS,
            threads_per_worker=DASK_THREADS_PER_WORKER,
            processes=True,
            memory_limit=DASK_MEMORY_LIMIT,
            dashboard_address=None,
        )
        DASK_CLIENT = Client(_dask_cluster)
        print(f"DASK local cluster active | workers={DASK_N_WORKERS} threads/worker={DASK_THREADS_PER_WORKER}")
    except Exception as ex:
        print(f"DASK disabled (fallback to serial execution): {ex}")
        DASK_CLIENT = None
        _dask_cluster = None

# Torch device (GPU if available, else CPU)
TORCH_DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("TORCH_DEVICE:", TORCH_DEVICE)

# Normalization from training domain [-2pi, 2pi] into encoding [-pi, pi]
base_frecuency, shift_feature = normalize_data(
    [TRAIN_INTERVAL[0]] * FEATURES_NUMBER,
    [TRAIN_INTERVAL[1]] * FEATURES_NUMBER,
    [ENCODING_INTERVAL[0]] * FEATURES_NUMBER,
    [ENCODING_INTERVAL[1]] * FEATURES_NUMBER,
)

print("base_frecuency:", base_frecuency)
print("shift_feature:", shift_feature)

## 2. Independent Configurations by Mode

You can edit each mode independently, without touching training functions.

In [11]:
MODE_CONFIGS = {
    "supervised": {
        "learning_rate": 0.005,
        "epochs": 50,
        "loss_weights": [0.9, 0.1],
        "train_sizes": [250, 500, 1000],
        "test_points": 100,
        "repetitions": 1,
        "beta1": 0.9,
        "beta2": 0.999,
        "tolerance": 1.0e-8,
        "n_counts_tolerance": 25,
        "print_step": 50,
        "batch_size": None,
        "n_qubits_by_feature": 3,
        "n_layers": 3,
        "debug_price_stats": True,
        "show_epoch_progress": True,
        "epoch_progress_leave": False,
    },
    "unsupervised": {
        "learning_rate": 0.1,
        "epochs": 50,
        "loss_weights": [0.2, 0.8],
        "train_sizes": [1000, 2500, 5000],
        "test_points": 1000,
        "repetitions": 1,
        "beta1": 0.9,
        "beta2": 0.999,
        "tolerance": 1.0e-8,
        "n_counts_tolerance": 25,
        "print_step": 50,
        "batch_size": None,
        "empirical_shift": -0.5,
        "n_qubits_by_feature": 2,
        "n_layers": 2,
        "debug_price_stats": True,
        "show_epoch_progress": True,
        "epoch_progress_leave": False,
    },
}

MODE_CONFIGS

{'supervised': {'learning_rate': 0.005,
  'epochs': 50,
  'loss_weights': [0.9, 0.1],
  'train_sizes': [250, 500, 1000],
  'test_points': 100,
  'repetitions': 1,
  'beta1': 0.9,
  'beta2': 0.999,
  'tolerance': 1e-08,
  'n_counts_tolerance': 25,
  'print_step': 50,
  'batch_size': None,
  'n_qubits_by_feature': 3,
  'n_layers': 3,
  'debug_price_stats': True,
  'show_epoch_progress': True,
  'epoch_progress_leave': False},
 'unsupervised': {'learning_rate': 0.1,
  'epochs': 50,
  'loss_weights': [0.2, 0.8],
  'train_sizes': [1000, 2500, 5000],
  'test_points': 1000,
  'repetitions': 1,
  'beta1': 0.9,
  'beta2': 0.999,
  'tolerance': 1e-08,
  'n_counts_tolerance': 25,
  'print_step': 50,
  'batch_size': None,
  'empirical_shift': -0.5,
  'n_qubits_by_feature': 2,
  'n_layers': 2,
  'debug_price_stats': True,
  'show_epoch_progress': True,
  'epoch_progress_leave': False}}

## 3. Helper Functions

In [ ]:
def build_mode_artifacts(cfg):
    pqc_cfg = {
        "features_number": FEATURES_NUMBER,
        "n_qubits_by_feature": int(cfg["n_qubits_by_feature"]),
        "n_layers": int(cfg["n_layers"]),
        "base_frecuency": list(base_frecuency),
        "shift_feature": list(shift_feature),
    }
    circuit_fn, weights_names, features_names = hardware_efficient_ansatz(**pqc_cfg)

    workflow_cfg = {
        "circuit_fn": circuit_fn,
        "weights_names": weights_names,
        "features_names": features_names,
        "torch_device": TORCH_DEVICE,
        "minval": [TRAIN_INTERVAL[0]],
        "maxval": [TRAIN_INTERVAL[1]],
        "points": 150,
    }
    return {
        "pqc_cfg": pqc_cfg,
        "weights_names": weights_names,
        "workflow_cfg": workflow_cfg,
    }


def batch_generator(X, Y, batch_size):
    return [(X[i : i + batch_size], Y[i : i + batch_size]) for i in range(0, len(X), batch_size)]


def run_supervised(u_train, cfg, artifacts, progress_desc=None):
    workflow_cfg = artifacts["workflow_cfg"]
    weights_names = artifacts["weights_names"]

    y_train = empirical_cdf(u_train).reshape((-1, 1)) - 0.5
    batch_size = cfg["batch_size"] if cfg["batch_size"] is not None else len(u_train)
    batches = batch_generator(u_train, y_train, batch_size)

    def training_loss(w_):
        return qdml_loss_workflow(
            w_, u_train, y_train, dask_client=DASK_CLIENT, loss_weights=cfg["loss_weights"], **workflow_cfg
        )

    def loss_for_grad(w_, x_, y_):
        return qdml_loss_workflow(
            w_, x_, y_, dask_client=DASK_CLIENT, loss_weights=cfg["loss_weights"], **workflow_cfg
        )

    def gradient_fn(w_, x_, y_):
        return torch_gradient(w_, x_, y_, loss_for_grad)

    optimizer_cfg = {
        "epochs": cfg["epochs"],
        "learning_rate": cfg["learning_rate"],
        "beta1": cfg["beta1"],
        "beta2": cfg["beta2"],
        "tolerance": cfg["tolerance"],
        "n_counts_tolerance": cfg["n_counts_tolerance"],
        "print_step": cfg["print_step"],
        "progress_bar": bool(cfg.get("show_epoch_progress", False)),
        "progress_desc": progress_desc if progress_desc is not None else "supervised epochs",
        "progress_leave": bool(cfg.get("epoch_progress_leave", False)),
    }

    initial_weights = init_weights(weights_names)
    return adam_optimizer_loop(
        weights_dict=initial_weights,
        loss_function=training_loss,
        metric_function=None,
        gradient_function=gradient_fn,
        batch_generator=batches,
        initial_time=0,
        **optimizer_cfg,
    )


def run_unsupervised(u_train, cfg, artifacts, progress_desc=None):
    workflow_cfg = artifacts["workflow_cfg"]
    weights_names = artifacts["weights_names"]

    dummy_y = np.zeros((u_train.shape[0], 1))
    batch_size = cfg["batch_size"] if cfg["batch_size"] is not None else len(u_train)
    batches = batch_generator(u_train, dummy_y, batch_size)

    def training_loss(w_):
        return unsupervised_qdml_loss_workflow(
            w_,
            u_train,
            dask_client=DASK_CLIENT,
            empirical_shift=cfg["empirical_shift"],
            loss_weights=cfg["loss_weights"],
            **workflow_cfg,
        )

    def loss_for_grad(w_, x_, y_):
        return unsupervised_qdml_loss_workflow(
            w_,
            x_,
            dask_client=DASK_CLIENT,
            empirical_shift=cfg["empirical_shift"],
            loss_weights=cfg["loss_weights"],
            **workflow_cfg,
        )

    def gradient_fn(w_, x_, y_):
        return torch_gradient(w_, x_, y_, loss_for_grad)

    optimizer_cfg = {
        "epochs": cfg["epochs"],
        "learning_rate": cfg["learning_rate"],
        "beta1": cfg["beta1"],
        "beta2": cfg["beta2"],
        "tolerance": cfg["tolerance"],
        "n_counts_tolerance": cfg["n_counts_tolerance"],
        "print_step": cfg["print_step"],
        "progress_bar": bool(cfg.get("show_epoch_progress", False)),
        "progress_desc": progress_desc if progress_desc is not None else "unsupervised epochs",
        "progress_leave": bool(cfg.get("epoch_progress_leave", False)),
    }

    initial_weights = init_weights(weights_names)
    return adam_optimizer_loop(
        weights_dict=initial_weights,
        loss_function=training_loss,
        metric_function=None,
        gradient_function=gradient_fn,
        batch_generator=batches,
        initial_time=0,
        **optimizer_cfg,
    )

## 4. Debug

Use these toggles before launching the full loop.

In [13]:
# Optional quick sanity mode
DEBUG_FAST_RUN = False

# More frequent progress logs (helps confirm the process is alive)
VERBOSE_PROGRESS = True

if VERBOSE_PROGRESS:
    for cfg in MODE_CONFIGS.values():
        cfg["print_step"] = min(int(cfg.get("print_step", 50)), 10)
        cfg["print_step"] = max(cfg["print_step"], 1)

if DEBUG_FAST_RUN:
    # tiny run to verify everything end-to-end before expensive execution
    for cfg in MODE_CONFIGS.values():
        cfg["epochs"] = min(int(cfg["epochs"]), 2)
        cfg["repetitions"] = 1
        cfg["train_sizes"] = [int(cfg["train_sizes"][0])]

MODE_CONFIGS

{'supervised': {'learning_rate': 0.005,
  'epochs': 50,
  'loss_weights': [0.9, 0.1],
  'train_sizes': [250, 500, 1000],
  'test_points': 100,
  'repetitions': 1,
  'beta1': 0.9,
  'beta2': 0.999,
  'tolerance': 1e-08,
  'n_counts_tolerance': 25,
  'print_step': 10,
  'batch_size': None,
  'n_qubits_by_feature': 3,
  'n_layers': 3,
  'debug_price_stats': True,
  'show_epoch_progress': True,
  'epoch_progress_leave': False},
 'unsupervised': {'learning_rate': 0.1,
  'epochs': 50,
  'loss_weights': [0.2, 0.8],
  'train_sizes': [1000, 2500, 5000],
  'test_points': 1000,
  'repetitions': 1,
  'beta1': 0.9,
  'beta2': 0.999,
  'tolerance': 1e-08,
  'n_counts_tolerance': 25,
  'print_step': 10,
  'batch_size': None,
  'empirical_shift': -0.5,
  'n_qubits_by_feature': 2,
  'n_layers': 2,
  'debug_price_stats': True,
  'show_epoch_progress': True,
  'epoch_progress_leave': False}}

In [14]:
def expected_total_runs(mode_configs, strikes):
    return sum(len(cfg["train_sizes"]) * len(strikes) * int(cfg["repetitions"]) for cfg in mode_configs.values())


def format_eta(seconds):
    if seconds is None or (not np.isfinite(seconds)):
        return "n/a"
    seconds = int(max(0, round(seconds)))
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    return f"{h:02d}:{m:02d}:{s:02d}"


def eta_from_partial(results_df, mode_configs, strikes):
    total_runs = expected_total_runs(mode_configs, strikes)
    done_runs = len(results_df)
    if done_runs == 0:
        return {"total_runs": total_runs, "done_runs": 0, "avg_sec_per_run": None, "eta_hours": None}
    avg_sec = float(results_df["seconds"].mean())
    pending = max(total_runs - done_runs, 0)
    eta_hours = (pending * avg_sec) / 3600.0
    return {
        "total_runs": total_runs,
        "done_runs": done_runs,
        "avg_sec_per_run": avg_sec,
        "eta_hours": eta_hours,
    }


USE_TQDM = True

# Usage after (or during) the main loop:
# eta_from_partial(results_df, MODE_CONFIGS, STRIKES)

## 4. Run Experiment

In [15]:
import os

os.environ["QML4VAR_PROFILE_TRAINING"] = "1"
os.environ["QML4VAR_PROFILE_EPOCHS"] = "1"
os.environ["QML4VAR_PROFILE_ONCE"] = "1"
os.environ["QML4VAR_PROFILE_LABEL"] = "first_case"

os.environ["QML4VAR_PROFILE_GRAD"] = "1"
os.environ["QML4VAR_PROFILE_GRAD_FIRST_ONLY"] = "1"

In [16]:
results = []
base_seed = 2026

mode_artifacts = {}
for mode_name, cfg in MODE_CONFIGS.items():
    artifacts = build_mode_artifacts(cfg)
    mode_artifacts[mode_name] = artifacts
    print(
        f"mode={mode_name} -> qubits_by_feature={cfg['n_qubits_by_feature']} "
        f"layers={cfg['n_layers']} total_weights={len(artifacts['weights_names'])}"
    )

total_runs = expected_total_runs(MODE_CONFIGS, STRIKES)
print(f"\nPlanned training runs: {total_runs}")

progress = tqdm(
    total=total_runs,
    desc="Training runs",
    unit="run",
    disable=not (USE_TQDM and TQDM_AVAILABLE),
)

run_counter = 0
global_t0 = perf_counter()

for mode_name, cfg in MODE_CONFIGS.items():
    artifacts = mode_artifacts[mode_name]
    print(f"\n=== Running mode: {mode_name} ===")
    for K_ in STRIKES:
        theor_price = bs_put_price(S0, K_, r, sigma, T)
        for n_train in cfg["train_sizes"]:
            n_test = int(cfg["test_points"])
            for rep in range(cfg["repetitions"]):
                seed = base_seed + 100000 * rep + 1000 * int(K_) + n_train
                n_total = n_train + n_test

                x_raw_all, u_all, x_min_raw, x_max_raw = simulate_black_scholes_data_rescaled(
                    S0_=S0, r_=r, T_=T, sigma_=sigma, K_=K_, n_points=n_total, seed=seed
                )
                u_train = u_all[:n_train]
                u_test = u_all[n_train:]

                t0 = perf_counter()
                epoch_desc = f"{mode_name} K={K_} n={n_train} rep={rep + 1}"
                if mode_name == "supervised":
                    weights = run_supervised(u_train, cfg, artifacts, progress_desc=epoch_desc)
                else:
                    weights = run_unsupervised(u_train, cfg, artifacts, progress_desc=epoch_desc)
                t1 = perf_counter()

                # Optional test metric (CDF MSE wrt empirical CDF on test split)
                y_test = empirical_cdf(u_test).reshape((-1, 1)) - 0.5
                y_pred_test = workflow_for_cdf(
                    weights, u_test, dask_client=DASK_CLIENT, **artifacts["workflow_cfg"]
                )["y_predict_cdf"].reshape((-1, 1))
                test_mse = float(np.mean((y_pred_test - y_test) ** 2))

                debug_label = f"mode={mode_name} K={K_} n_train={n_train} rep={rep + 1}"
                est_price = estimate_price_from_trained_pqc(
                    weights=weights,
                    artifacts=artifacts,
                    K_=K_,
                    x_min_raw=x_min_raw,
                    x_max_raw=x_max_raw,
                    train_interval=TRAIN_INTERVAL,
                    risk_free_rate=r,
                    delta_t=T,
                    k_terms=K_TERMS,
                    grid_points=GRID_POINTS_FOURIER,
                    dask_client=DASK_CLIENT,
                    debug=bool(cfg.get("debug_price_stats", False)),
                    debug_label=debug_label,
                )

                run_seconds = float(t1 - t0)
                results.append({
                    "mode": mode_name,
                    "strike": K_,
                    "dataset_size": n_train,
                    "test_points": n_test,
                    "rep": rep + 1,
                    "estimated_price": est_price,
                    "theoretical_price": float(theor_price),
                    "test_mse": test_mse,
                    "seconds": run_seconds,
                    "n_qubits_by_feature": int(cfg["n_qubits_by_feature"]),
                    "n_layers": int(cfg["n_layers"]),
                })

                run_counter += 1
                elapsed = perf_counter() - global_t0
                avg_per_run = elapsed / max(run_counter, 1)
                eta_seconds = (total_runs - run_counter) * avg_per_run

                progress.update(1)
                progress.set_postfix({
                    "mode": mode_name,
                    "K": K_,
                    "n": n_train,
                    "rep": rep + 1,
                    "run_s": f"{run_seconds:.1f}",
                    "eta": format_eta(eta_seconds),
                })

                print(
                    f"mode={mode_name} K={K_} n_train={n_train} rep={rep + 1} "
                    f"price={est_price:.6f} run_s={run_seconds:.2f} ETA={format_eta(eta_seconds)}"
                )

progress.close()

total_elapsed = perf_counter() - global_t0
print(f"\nCompleted {run_counter}/{total_runs} runs in {format_eta(total_elapsed)}")

results_df = pd.DataFrame(results)
results_df.head()

mode=supervised -> qubits_by_feature=3 layers=3 total_weights=9
mode=unsupervised -> qubits_by_feature=2 layers=2 total_weights=4

Planned training runs: 18

Training runs:   0%|          | 0/18 [05:58<?, ?run/s]

=== Running mode: supervised ===

supervised K=90 n=250 rep=1:   0%|          | 0/50 [00:00<?, ?epoch/s]

[PROFILE GRAD] weights=9 loss_evals=18 eval_mean_s=12.540 eval_max_s=16.638 total_grad_s=225.719

supervised K=90 n=250 rep=1:   2%|▏         | 1/50 [04:20<3:32:55, 260.71s/epoch, loss=2.362e-01, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 0.2361707400604107
[PROFILE first_case] epoch=0 batches=1 grad_s=225.719 update_s=0.000 loss_s=16.892 metric_s=0.000 misc_s=0.012 total_s=242.623

supervised K=90 n=250 rep=1:  22%|██▏       | 11/50 [46:46<2:41:41, 248.75s/epoch, loss=1.840e-01, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.18396187483010273

supervised K=90 n=250 rep=1:  42%|████▏     | 21/50 [1:27:48<2:07:31, 263.83s/epoch, loss=1.381e-01, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.13814150454383778

supervised K=90 n=250 rep=1:  62%|██████▏   | 31/50 [2:14:59<1:38:52, 312.22s/epoch, loss=1.008e-01, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: 0.10076138960527094

supervised K=90 n=250 rep=1:  82%|████████▏ | 41/50 [4:39:54<2:05:14, 834.99s/epoch, loss=7.377e-02, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: 0.07377266057075918

Maximum number of iterations achieved.

[PRICE DEBUG] mode=supervised K=90 n_train=250 rep=1 pdf_min=0.000000e+00 pdf_max=3.162918e-01 area=1.304484e+00
mode=supervised K=90 n_train=250 rep=1 price=4.361197 run_s=13209.84 ETA=62:32:46

supervised K=90 n=500 rep=1:   2%|▏         | 1/50 [08:10<6:40:51, 490.84s/epoch, loss=2.191e-01, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 0.21914960072399994

supervised K=90 n=500 rep=1:  22%|██▏       | 11/50 [1:31:13<5:13:49, 482.81s/epoch, loss=1.868e-01, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.18676018354666704

supervised K=90 n=500 rep=1:  42%|████▏     | 21/50 [2:45:23<3:25:04, 424.28s/epoch, loss=1.560e-01, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.1560029947930543

supervised K=90 n=500 rep=1:  62%|██████▏   | 31/50 [10:41:58<15:32:53, 2945.97s/epoch, loss=1.293e-01, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: 0.12927549112413028

supervised K=90 n=500 rep=1:  82%|████████▏ | 41/50 [14:27:13<2:38:49, 1058.83s/epoch, loss=1.076e-01, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: 0.10764099160530244

Maximum number of iterations achieved.

[PRICE DEBUG] mode=supervised K=90 n_train=500 rep=1 pdf_min=0.000000e+00 pdf_max=5.568735e-01 area=1.311658e+00
mode=supervised K=90 n_train=500 rep=1 price=1.149780 run_s=22134.62 ETA=78:42:28

supervised K=90 n=1000 rep=1:   2%|▏         | 1/50 [11:46<9:36:58, 706.50s/epoch, loss=1.689e-01, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 0.1689125071088523

supervised K=90 n=1000 rep=1:  22%|██▏       | 11/50 [6:38:07<54:29:00, 5029.24s/epoch, loss=1.187e-01, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.11866301399017173

supervised K=90 n=1000 rep=1:  42%|████▏     | 21/50 [8:53:44<7:05:20, 880.02s/epoch, loss=7.961e-02, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.07961141529274265

supervised K=90 n=1000 rep=1:  62%|██████▏   | 31/50 [10:51:35<3:43:52, 706.99s/epoch, loss=5.156e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: 0.051556902492394356

supervised K=90 n=1000 rep=1:  82%|████████▏ | 41/50 [19:19:53<10:47:52, 4319.14s/epoch, loss=3.429e-02, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: 0.03428875015979745

Maximum number of iterations achieved.

[PRICE DEBUG] mode=supervised K=90 n_train=1000 rep=1 pdf_min=0.000000e+00 pdf_max=4.996779e-01 area=1.210122e+00
mode=supervised K=90 n_train=1000 rep=1 price=1.734323 run_s=37153.93 ETA=100:51:34

supervised K=100 n=250 rep=1:   2%|▏         | 1/50 [04:29<3:39:55, 269.30s/epoch, loss=2.611e-01, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 0.2610661957486788

supervised K=100 n=250 rep=1:  22%|██▏       | 11/50 [44:41<2:38:43, 244.18s/epoch, loss=2.087e-01, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.2086759748454404

supervised K=100 n=250 rep=1:  42%|████▏     | 21/50 [1:23:14<1:49:59, 227.55s/epoch, loss=1.694e-01, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.16944396686169838

supervised K=100 n=250 rep=1:  62%|██████▏   | 31/50 [2:03:46<1:18:41, 248.50s/epoch, loss=1.432e-01, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: 0.14320189061951596

supervised K=100 n=250 rep=1:  82%|████████▏ | 41/50 [3:37:39<1:21:56, 546.33s/epoch, loss=1.254e-01, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: 0.1254069088997219

Maximum number of iterations achieved.

[PRICE DEBUG] mode=supervised K=100 n_train=250 rep=1 pdf_min=0.000000e+00 pdf_max=5.710022e-01 area=1.402145e+00
mode=supervised K=100 n_train=250 rep=1 price=2.359303 run_s=12230.54 ETA=82:31:14

supervised K=100 n=500 rep=1:   2%|▏         | 1/50 [07:29<6:07:20, 449.80s/epoch, loss=8.338e-02, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 0.08337548690677976

supervised K=100 n=500 rep=1:  22%|██▏       | 11/50 [1:30:34<4:27:46, 411.96s/epoch, loss=5.958e-02, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.05957990424554328

supervised K=100 n=500 rep=1:  42%|████▏     | 21/50 [2:51:42<5:26:29, 675.51s/epoch, loss=4.173e-02, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.041732970485823986

supervised K=100 n=500 rep=1:  62%|██████▏   | 31/50 [4:00:10<2:07:54, 403.90s/epoch, loss=2.864e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: 0.028635449106244888

supervised K=100 n=500 rep=1:  72%|███████▏  | 36/50 [4:32:51<1:32:31, 396.51s/epoch, loss=2.317e-02, n_tol=0]2026-03-12 20:11:20,372 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('lambda-c61e153b121cb0d829b0e2626ac8e27a')" coro=<Worker.execute() done, defined at /home/vscode/.local/lib/python3.12/site-packages/distributed/worker_state_machine.py:3608>> ended with CancelledError
2026-03-12 20:11:24,941 - distributed.nanny - WARNING - Restarting worker
supervised K=100 n=500 rep=1:  82%|████████▏ | 41/50 [6:18:22<1:52:52, 752.54s/epoch, loss=1.822e-02, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: 0.01822273596346464

Maximum number of iterations achieved.

[PRICE DEBUG] mode=supervised K=100 n_train=500 rep=1 pdf_min=0.000000e+00 pdf_max=3.073213e-01 area=8.820203e-01
mode=supervised K=100 n_train=500 rep=1 price=2.490515 run_s=21970.75 ETA=77:11:25

supervised K=100 n=1000 rep=1:   2%|▏         | 1/50 [15:12<12:24:48, 912.00s/epoch, loss=2.059e-01, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 0.20592680939388625

supervised K=100 n=1000 rep=1:  22%|██▏       | 11/50 [9:10:57<18:24:33, 1699.33s/epoch, loss=1.408e-01, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.14079052427010671

supervised K=100 n=1000 rep=1:  42%|████▏     | 21/50 [12:19:52<17:37:19, 2187.56s/epoch, loss=8.824e-02, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.08823950223632414

supervised K=100 n=1000 rep=1:  62%|██████▏   | 31/50 [14:42:31<4:13:41, 801.15s/epoch, loss=5.157e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: 0.051574600202664196

supervised K=100 n=1000 rep=1:  82%|████████▏ | 41/50 [16:38:41<1:40:50, 672.30s/epoch, loss=2.910e-02, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: 0.02909632576791135

Maximum number of iterations achieved.

[PRICE DEBUG] mode=supervised K=100 n_train=1000 rep=1 pdf_min=0.000000e+00 pdf_max=3.552628e-01 area=1.050963e+00
mode=supervised K=100 n_train=1000 rep=1 price=5.422773 run_s=34645.35 ETA=78:38:20

supervised K=110 n=250 rep=1:   2%|▏         | 1/50 [03:32<2:53:18, 212.22s/epoch, loss=1.005e-01, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 0.10053961905679054

supervised K=110 n=250 rep=1:  22%|██▏       | 11/50 [2:01:03<10:03:49, 928.95s/epoch, loss=5.993e-02, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.059929336989223994

supervised K=110 n=250 rep=1:  42%|████▏     | 21/50 [2:38:21<1:55:05, 238.14s/epoch, loss=3.278e-02, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.03277913738220676

supervised K=110 n=250 rep=1:  62%|██████▏   | 31/50 [3:15:24<1:07:25, 212.93s/epoch, loss=1.759e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: 0.017594129186171224

supervised K=110 n=250 rep=1:  82%|████████▏ | 41/50 [3:54:57<34:48, 232.06s/epoch, loss=9.305e-03, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: 0.009305449847260658

Maximum number of iterations achieved.

[PRICE DEBUG] mode=supervised K=110 n_train=250 rep=1 pdf_min=0.000000e+00 pdf_max=3.990333e-01 area=9.045994e-01
mode=supervised K=110 n_train=250 rep=1 price=6.709539 run_s=11648.63 ETA=66:53:13

supervised K=110 n=500 rep=1:   2%|▏         | 1/50 [06:16<5:07:40, 376.74s/epoch, loss=1.006e-01, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 0.10058179212744209

supervised K=110 n=500 rep=1:  22%|██▏       | 11/50 [1:10:21<3:58:43, 367.28s/epoch, loss=7.162e-02, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.07162095451207569

supervised K=110 n=500 rep=1:  42%|████▏     | 21/50 [3:37:33<12:56:28, 1606.49s/epoch, loss=4.939e-02, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.04938735086766376

supervised K=110 n=500 rep=1:  62%|██████▏   | 31/50 [13:47:22<15:21:09, 2908.91s/epoch, loss=3.371e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: 0.03370772379754857

supervised K=110 n=500 rep=1:  82%|████████▏ | 41/50 [14:46:17<1:02:01, 413.49s/epoch, loss=2.355e-02, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: 0.023554228841702263

Maximum number of iterations achieved.

[PRICE DEBUG] mode=supervised K=110 n_train=500 rep=1 pdf_min=0.000000e+00 pdf_max=5.154119e-01 area=1.250337e+00
mode=supervised K=110 n_train=500 rep=1 price=13.247052 run_s=18098.23 ETA=59:29:54

supervised K=110 n=1000 rep=1:   2%|▏         | 1/50 [11:21<9:16:15, 681.13s/epoch, loss=3.385e-01, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 0.3384913643271209

supervised K=110 n=1000 rep=1:  22%|██▏       | 11/50 [1:48:06<6:38:37, 613.27s/epoch, loss=2.733e-01, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.2733217612041152

supervised K=110 n=1000 rep=1:  42%|████▏     | 21/50 [3:24:52<4:41:07, 581.65s/epoch, loss=2.057e-01, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.20567128314035826

supervised K=110 n=1000 rep=1:  62%|██████▏   | 31/50 [6:21:35<4:03:23, 768.63s/epoch, loss=1.455e-01, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: 0.14549788773443034

supervised K=110 n=1000 rep=1:  82%|████████▏ | 41/50 [8:09:32<1:35:23, 635.97s/epoch, loss=1.009e-01, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: 0.100856658144518

Maximum number of iterations achieved.

[PRICE DEBUG] mode=supervised K=110 n_train=1000 rep=1 pdf_min=0.000000e+00 pdf_max=3.890484e-01 area=1.321827e+00
mode=supervised K=110 n_train=1000 rep=1 price=12.785986 run_s=30986.42 ETA=56:12:46

=== Running mode: unsupervised ===

unsupervised K=90 n=1000 rep=1:   2%|▏         | 1/50 [18:08<14:48:53, 1088.43s/epoch, loss=2.369e+00, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 2.3692388278073793

unsupervised K=90 n=1000 rep=1:  22%|██▏       | 11/50 [3:49:22<13:24:35, 1237.83s/epoch, loss=-9.622e-03, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: -0.009622195193874186

unsupervised K=90 n=1000 rep=1:  42%|████▏     | 21/50 [5:15:59<1:49:22, 226.31s/epoch, loss=2.841e-03, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.0028406087483398984

unsupervised K=90 n=1000 rep=1:  62%|██████▏   | 31/50 [5:32:34<33:46, 106.66s/epoch, loss=-3.109e-02, n_tol=5]

	 MSE at t=30: None
	 Iteracion: 30. Loss: -0.0310937387236574

unsupervised K=90 n=1000 rep=1:  82%|████████▏ | 41/50 [6:21:38<1:15:39, 504.35s/epoch, loss=-5.451e-02, n_tol=1]

	 MSE at t=40: None
	 Iteracion: 40. Loss: -0.054512286194774565

Maximum number of iterations achieved.

[PRICE DEBUG] mode=unsupervised K=90 n_train=1000 rep=1 pdf_min=0.000000e+00 pdf_max=8.661358e-02 area=4.109726e-01
mode=unsupervised K=90 n_train=1000 rep=1 price=9.667644 run_s=5047.11 ETA=46:05:38

unsupervised K=90 n=2500 rep=1:   2%|▏         | 1/50 [04:15<3:28:47, 255.66s/epoch, loss=1.505e+00, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 1.5054764825309064

unsupervised K=90 n=2500 rep=1:  22%|██▏       | 11/50 [45:17<2:56:35, 271.67s/epoch, loss=-5.789e-02, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: -0.0578878809040401

unsupervised K=90 n=2500 rep=1:  42%|████▏     | 21/50 [5:43:23<21:13:44, 2635.33s/epoch, loss=3.471e-02, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.034714973984166515

unsupervised K=90 n=2500 rep=1:  62%|██████▏   | 31/50 [7:23:37<2:00:28, 380.47s/epoch, loss=-5.560e-02, n_tol=1]

	 MSE at t=30: None
	 Iteracion: 30. Loss: -0.0556014453357361

unsupervised K=90 n=2500 rep=1:  82%|████████▏ | 41/50 [8:06:45<40:56, 272.90s/epoch, loss=-4.727e-02, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: -0.04726612391504637

Maximum number of iterations achieved.

[PRICE DEBUG] mode=unsupervised K=90 n_train=2500 rep=1 pdf_min=0.000000e+00 pdf_max=1.362332e-01 area=5.464116e-01
mode=unsupervised K=90 n_train=2500 rep=1 price=14.940372 run_s=12571.06 ETA=38:53:23

unsupervised K=90 n=5000 rep=1:   2%|▏         | 1/50 [08:32<6:58:20, 512.26s/epoch, loss=1.438e+00, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 1.4377194631495072

unsupervised K=90 n=5000 rep=1:  22%|██▏       | 11/50 [1:33:37<5:45:38, 531.76s/epoch, loss=-7.043e-02, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: -0.07042738887898739

unsupervised K=90 n=5000 rep=1:  42%|████▏     | 21/50 [5:14:32<21:54:03, 2718.75s/epoch, loss=-4.327e-03, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: -0.0043274008783514666

unsupervised K=90 n=5000 rep=1:  56%|█████▌    | 28/50 [13:36:47<15:37:55, 2557.99s/epoch, loss=-5.669e-02, n_tol=0]2026-03-16 09:51:48,502 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('lambda-f692215fdf4c4d2fb834f585fc8c998e')" coro=<Worker.execute() done, defined at /home/vscode/.local/lib/python3.12/site-packages/distributed/worker_state_machine.py:3608>> ended with CancelledError
2026-03-16 09:51:48,504 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('lambda-d114d9ac22ec7344a8c3a654d6b9007b')" coro=<Worker.execute() done, defined at /home/vscode/.local/lib/python3.12/site-packages/distributed/worker_state_machine.py:3608>> ended with CancelledError
2026-03-16 09:51:48,744 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('lambda-403a7f8d6e1d6968ef12dc966ea7f369')" coro=<Worker.execute() done, defined at /home/vscode/.local/lib/python3.12/site-packages/distributed/worker_state_machine.py:3608>> ended with CancelledError
2026-03-16 09:51:49,802 - distributed.nanny - WARNING - Restarting worker
2026-03-16 09:51:49,809 - distributed.nanny - WARNING - Restarting worker
2026-03-16 09:51:49,811 - distributed.nanny - WARNING - Restarting worker
2026-03-16 09:51:49,813 - distributed.nanny - WARNING - Restarting worker
unsupervised K=90 n=5000 rep=1:  62%|██████▏   | 31/50 [15:11:01<9:39:32, 1830.14s/epoch, loss=-6.460e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: -0.06460301437813012

unsupervised K=90 n=5000 rep=1:  82%|████████▏ | 41/50 [17:43:27<1:58:01, 786.80s/epoch, loss=-5.834e-02, n_tol=9]

	 MSE at t=40: None
	 Iteracion: 40. Loss: -0.058338731693317755

Maximum number of iterations achieved.

[PRICE DEBUG] mode=unsupervised K=90 n_train=5000 rep=1 pdf_min=0.000000e+00 pdf_max=1.094215e-01 area=4.335722e-01
mode=unsupervised K=90 n_train=5000 rep=1 price=14.433670 run_s=25726.22 ETA=34:07:51

unsupervised K=100 n=1000 rep=1:   2%|▏         | 1/50 [02:49<2:18:26, 169.53s/epoch, loss=1.347e+00, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 1.3470717909284802

unsupervised K=100 n=1000 rep=1:  22%|██▏       | 11/50 [25:21<1:38:27, 151.47s/epoch, loss=-3.814e-02, n_tol=2]

	 MSE at t=10: None
	 Iteracion: 10. Loss: -0.03813974453089367

unsupervised K=100 n=1000 rep=1:  42%|████▏     | 21/50 [57:09<2:33:05, 316.75s/epoch, loss=-5.733e-02, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: -0.05732887755518292

unsupervised K=100 n=1000 rep=1:  62%|██████▏   | 31/50 [1:16:18<36:41, 115.87s/epoch, loss=-4.764e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: -0.047639275409525145

unsupervised K=100 n=1000 rep=1:  82%|████████▏ | 41/50 [1:34:06<16:04, 107.15s/epoch, loss=-5.951e-02, n_tol=3]

	 MSE at t=40: None
	 Iteracion: 40. Loss: -0.059505255994927495

Maximum number of iterations achieved.

[PRICE DEBUG] mode=unsupervised K=100 n_train=1000 rep=1 pdf_min=0.000000e+00 pdf_max=1.141246e-01 area=4.919948e-01
mode=unsupervised K=100 n_train=1000 rep=1 price=17.058142 run_s=6085.84 ETA=26:54:20

unsupervised K=100 n=2500 rep=1:   2%|▏         | 1/50 [03:57<3:14:06, 237.68s/epoch, loss=7.966e-01, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 0.7965618378192321

unsupervised K=100 n=2500 rep=1:  22%|██▏       | 11/50 [48:47<2:49:59, 261.54s/epoch, loss=5.416e-02, n_tol=4]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.054159080535837664

unsupervised K=100 n=2500 rep=1:  42%|████▏     | 21/50 [1:29:34<2:02:11, 252.79s/epoch, loss=-5.827e-02, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: -0.05827247937221067

unsupervised K=100 n=2500 rep=1:  62%|██████▏   | 31/50 [2:12:23<1:14:10, 234.21s/epoch, loss=-5.945e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: -0.05944937113735314

unsupervised K=100 n=2500 rep=1:  82%|████████▏ | 41/50 [3:54:19<3:26:26, 1376.29s/epoch, loss=-6.068e-02, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: -0.06067923157794073

Maximum number of iterations achieved.

[PRICE DEBUG] mode=unsupervised K=100 n_train=2500 rep=1 pdf_min=0.000000e+00 pdf_max=1.363349e-01 area=5.514075e-01
mode=unsupervised K=100 n_train=2500 rep=1 price=19.597411 run_s=12754.55 ETA=21:00:01

unsupervised K=100 n=5000 rep=1:   2%|▏         | 1/50 [08:14<6:43:43, 494.35s/epoch, loss=2.118e+00, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 2.1182501192866874

unsupervised K=100 n=5000 rep=1:  22%|██▏       | 11/50 [11:13:11<86:49:31, 8014.66s/epoch, loss=-3.530e-02, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: -0.035303717611709994

unsupervised K=100 n=5000 rep=1:  42%|████▏     | 21/50 [13:38:26<6:39:50, 827.25s/epoch, loss=5.597e-02, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.055967337675998416

unsupervised K=100 n=5000 rep=1:  62%|██████▏   | 31/50 [14:55:18<2:25:36, 459.82s/epoch, loss=-5.370e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: -0.05369867211939641

unsupervised K=100 n=5000 rep=1:  82%|████████▏ | 41/50 [17:09:25<1:48:10, 721.19s/epoch, loss=-3.919e-02, n_tol=0]

	 MSE at t=40: None
	 Iteracion: 40. Loss: -0.0391909842460895

Maximum number of iterations achieved.

[PRICE DEBUG] mode=unsupervised K=100 n_train=5000 rep=1 pdf_min=0.000000e+00 pdf_max=1.057731e-01 area=4.235009e-01
mode=unsupervised K=100 n_train=5000 rep=1 price=18.532472 run_s=25263.47 ETA=16:06:15

unsupervised K=110 n=1000 rep=1:   2%|▏         | 1/50 [01:51<1:31:07, 111.59s/epoch, loss=2.269e+00, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 2.2689420539010303

unsupervised K=110 n=1000 rep=1:  22%|██▏       | 11/50 [21:57<1:21:02, 124.68s/epoch, loss=1.238e-01, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.12375493588915817

unsupervised K=110 n=1000 rep=1:  42%|████▏     | 21/50 [39:57<51:14, 106.00s/epoch, loss=9.208e-02, n_tol=6]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.09208337734926104

unsupervised K=110 n=1000 rep=1:  62%|██████▏   | 31/50 [58:01<34:41, 109.55s/epoch, loss=-1.678e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: -0.016777381208963743

unsupervised K=110 n=1000 rep=1:  82%|████████▏ | 41/50 [1:31:15<38:11, 254.65s/epoch, loss=-3.095e-02, n_tol=6]

	 MSE at t=40: None
	 Iteracion: 40. Loss: -0.03095499828293734

Maximum number of iterations achieved.

[PRICE DEBUG] mode=unsupervised K=110 n_train=1000 rep=1 pdf_min=0.000000e+00 pdf_max=1.099722e-01 area=4.304085e-01
mode=unsupervised K=110 n_train=1000 rep=1 price=25.095112 run_s=6003.01 ETA=10:16:26

unsupervised K=110 n=2500 rep=1:   2%|▏         | 1/50 [52:14<42:40:14, 3134.99s/epoch, loss=1.976e+00, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 1.9755283777959596

unsupervised K=110 n=2500 rep=1:  22%|██▏       | 11/50 [2:27:39<3:29:49, 322.80s/epoch, loss=2.798e-01, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: 0.2798268811064436

unsupervised K=110 n=2500 rep=1:  42%|████▏     | 21/50 [3:21:21<2:25:19, 300.67s/epoch, loss=4.872e-02, n_tol=5]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.048719892151063086

unsupervised K=110 n=2500 rep=1:  62%|██████▏   | 31/50 [4:10:27<1:23:52, 264.85s/epoch, loss=-7.199e-03, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: -0.007199355033047727

unsupervised K=110 n=2500 rep=1:  82%|████████▏ | 41/50 [4:50:22<34:44, 231.65s/epoch, loss=-5.985e-02, n_tol=3]

	 MSE at t=40: None
	 Iteracion: 40. Loss: -0.0598491994969413

Maximum number of iterations achieved.

[PRICE DEBUG] mode=unsupervised K=110 n_train=2500 rep=1 pdf_min=0.000000e+00 pdf_max=8.071342e-02 area=3.529597e-01
mode=unsupervised K=110 n_train=2500 rep=1 price=21.343050 run_s=14108.33 ETA=05:03:56

unsupervised K=110 n=5000 rep=1:   2%|▏         | 1/50 [07:32<6:09:45, 452.76s/epoch, loss=1.165e+00, n_tol=0]

	 MSE at t=0: None
	 Iteracion: 0. Loss: 1.1645987467348882

unsupervised K=110 n=5000 rep=1:  22%|██▏       | 11/50 [7:24:54<25:35:22, 2362.12s/epoch, loss=-4.999e-02, n_tol=0]

	 MSE at t=10: None
	 Iteracion: 10. Loss: -0.049994839537980965

unsupervised K=110 n=5000 rep=1:  42%|████▏     | 21/50 [8:45:38<4:26:58, 552.38s/epoch, loss=4.649e-02, n_tol=0]

	 MSE at t=20: None
	 Iteracion: 20. Loss: 0.04649231019095121

unsupervised K=110 n=5000 rep=1:  62%|██████▏   | 31/50 [10:06:11<2:33:50, 485.83s/epoch, loss=-3.508e-02, n_tol=0]

	 MSE at t=30: None
	 Iteracion: 30. Loss: -0.03508258765651557

unsupervised K=110 n=5000 rep=1:  82%|████████▏ | 41/50 [11:56:16<2:19:39, 931.03s/epoch, loss=-2.964e-02, n_tol=7]

	 MSE at t=40: None
	 Iteracion: 40. Loss: -0.029644148568517124

Maximum number of iterations achieved.

Training runs: 100%|██████████| 18/18 [191:33:35<00:00, 38311.99s/run, mode=unsupervised, K=110, n=5000, rep=1, run_s=24642.5, eta=00:00:00]

[PRICE DEBUG] mode=unsupervised K=110 n_train=5000 rep=1 pdf_min=0.000000e+00 pdf_max=8.843955e-02 area=3.539901e-01
mode=unsupervised K=110 n_train=5000 rep=1 price=20.028955 run_s=24642.45 ETA=00:00:00

Completed 18/18 runs in 92:57:39

,mode,strike,dataset_size,test_points,rep,estimated_price,theoretical_price,test_mse,seconds,n_qubits_by_feature,n_layers
0,supervised,90,250,100,1,4.361197,2.598827,0.020666,13209.840609,3,3
1,supervised,90,500,100,1,1.149780,2.598827,0.070541,22134.616456,3,3
2,supervised,90,1000,100,1,1.734323,2.598827,0.011726,37153.930585,3,3
3,supervised,100,250,100,1,2.359303,5.459533,0.043246,12230.537134,3,3
4,supervised,100,500,100,1,2.490515,5.459533,0.015662,21970.750438,3,3

## 5. Summaries

In [17]:
summary_df = results_df.groupby(["mode", "strike", "dataset_size"], as_index=False).agg(
    mean_price=("estimated_price", "mean"),
    std_price=("estimated_price", "std"),
    mean_test_mse=("test_mse", "mean"),
    mean_seconds=("seconds", "mean"),
)
summary_df

,mode,strike,dataset_size,mean_price,std_price,mean_test_mse,mean_seconds
0,supervised,90,250,4.361197,NaN,0.020666,13209.840609
1,supervised,90,500,1.149780,NaN,0.070541,22134.616456
2,supervised,90,1000,1.734323,NaN,0.011726,37153.930585
3,supervised,100,250,2.359303,NaN,0.043246,12230.537134
4,supervised,100,500,2.490515,NaN,0.015662,21970.750438
5,supervised,100,1000,5.422773,NaN,0.024551,34645.353207
6,supervised,110,250,6.709539,NaN,0.017790,11648.625018
7,supervised,110,500,13.247052,NaN,0.007892,18098.225332
8,supervised,110,1000,12.785986,NaN,0.031156,30986.422247
9,unsupervised,90,1000,9.667644,NaN,0.046187,5047.110141
10,unsupervised,90,2500,14.940372,NaN,0.040878,12571.055808
11,unsupervised,90,5000,14.433670,NaN,0.051102,25726.223340
12,unsupervised,100,1000,17.058142,NaN,0.042972,6085.840210
13,unsupervised,100,2500,19.597411,NaN,0.041443,12754.553647
14,unsupervised,100,5000,18.532472,NaN,0.049496,25263.468084
15,unsupervised,110,1000,25.095112,NaN,0.052673,6003.012861
16,unsupervised,110,2500,21.343050,NaN,0.054760,14108.326540
17,unsupervised,110,5000,20.028955,NaN,0.055360,24642.453071

## 6. Price Curves by Dataset Size

In [ ]:
colors = ["#377eb8", "#ff7f00", "#4daf4a"]

for mode_name, cfg in MODE_CONFIGS.items():
    dataset_sizes = cfg["train_sizes"]
    df_mode = results_df[results_df["mode"] == mode_name].copy()

    plt.figure(figsize=(10, 7))

    for K_, color in zip(STRIKES, colors, strict=False):
        df_k = df_mode[df_mode["strike"] == K_]

        means = []
        stds = []
        for n_ in dataset_sizes:
            vals = df_k[df_k["dataset_size"] == n_]["estimated_price"].values
            means.append(np.nanmean(vals) if vals.size > 0 else np.nan)
            stds.append(np.nanstd(vals, ddof=1) if vals.size > 1 else 0.0)

        plt.errorbar(
            dataset_sizes,
            means,
            yerr=stds,
            fmt="-o",
            color=color,
            label=f"K = {K_}",
            capsize=5,
            markersize=8,
            elinewidth=1.5,
        )

        # Theoretical line for each strike
        p_theo = bs_put_price(S0, K_, r, sigma, T)
        plt.axhline(p_theo, color=color, linestyle="--", linewidth=0.9, alpha=0.9)

        # Outliers by IQR
        for n_ in dataset_sizes:
            vals = df_k[df_k["dataset_size"] == n_]["estimated_price"].dropna().values
            if vals.size < 4:
                continue
            q1, q3 = np.percentile(vals, [25, 75])
            iqr = q3 - q1
            low = q1 - 1.5 * iqr
            high = q3 + 1.5 * iqr
            outliers = vals[(vals < low) | (vals > high)]
            if outliers.size > 0:
                plt.scatter(
                    np.full(outliers.shape[0], n_),
                    outliers,
                    marker="x",
                    color=color,
                    s=45,
                    alpha=0.95,
                    label=f"Outliers K={K_}" if n_ == dataset_sizes[0] else None,
                )

    plt.title(f"Estimated prices by dataset size | mode={mode_name} | test_points={cfg['test_points']}")
    plt.xlabel("Size of the dataset (n_train)")
    plt.ylabel("Price")
    plt.xticks(dataset_sizes)
    plt.grid(alpha=0.25, axis="y")
    plt.legend(loc="best")
    plt.tight_layout()
    plt.show()

## 7. Optional Dask Cleanup

In [19]:
if DASK_CLIENT is not None:
    DASK_CLIENT.close()
if _dask_cluster is not None:
    _dask_cluster.close()
print("DASK resources closed")

DASK resources closed